=head1 NAME

Temma::Exception - Temma exception object

=head1 DESCRIPTION

The C<Temma::Exception> class is used to implement the interface for
the Temma exception object.  For more information, see
L<Temma::Language>.

=head1 SEE ALSO

L<Temma::Language>, L<Temma::Processor>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2012 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
