=head1 NAME

Temma::Parser - A parser for Temma template language

=head1 SYNOPSIS

XXX

=head1 DESCRIPTION

XXX

=head1 SEE ALSO

L<Temma>, L<Temma::Language>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2012 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
